// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Generate(arg1:string,arg2:number,arg3:number,arg4:boolean,arg5:string):Promise<string>;

export function TextToPoints(arg1:string):Promise<string>;
